# -*- coding: utf-8 -*-
"""Proy_Blue_If anidados

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UwvrvkSeQrXm5ppNaQjunWgyBQcTEoJm

#Tarea del correo

##Suma
"""

x=5
y=50
z=x+y
z

"""##Resta"""

x2=90
y2=150
z2=x2-y2
z2

"""##Multiplicación"""

x3=50
y3=80
z3=x3*y3
z3

"""##División"""

x4=90;y4=80
z4=x4/y4
z4,x4//y4

"""##Residuo"""

x5=103;y5=33
z5=x5%y5
z5

